### ISSUE TITLE
$ko^zvl*xH7b9hDRxi_4Tx^OIbq4xL2c

### ISSUE THREAD

**Issue by vastoa** [Protocol1337/SSH-API-DDoS-#1]

**Comment by pxladin** [comment]
you dont even use semantic commit messages

**Comment by pxladin** [comment]
https://karma-runner.github.io/6.3/dev/git-commit-msg.html you should use this

**Comment by pxladin** [comment]
![image](https://user-images.githubusercontent.com/31286564/114422753-d97af800-9bb6-11eb-88bb-cfb0da40a993.png)
and wtf is this?
